# -*- coding: utf-8 -*-
"""Copy of virtualtryon_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVII_y2YaJ6Ty5BaJhlAquCB3auv-JWv

# 👗 Virtual Try-On — SDXL + IP-Adapter

Upload a **model image** and a **clothing image**, and this notebook will generate a realistic photo of the model wearing that clothing.

**How it works:**
1. Segments the human body using SegFormer
2. Detects and preserves the face using InsightFace
3. Uses SDXL Inpainting + IP-Adapter to virtually dress the model

---
⚠️ **Before running:** Go to `Runtime > Change runtime type` and set Hardware Accelerator to **GPU (T4)**.
"""

# ── Cell 1: Install dependencies ──────────────────────────────────────────────
!pip install -q diffusers accelerate insightface onnxruntime-gpu transformers
print("✅ Dependencies installed")

# ── Cell 2: Check GPU ─────────────────────────────────────────────────────────
import torch

if not torch.cuda.is_available():
    raise RuntimeError("❌ No GPU detected. Go to Runtime > Change runtime type and select GPU.")

print(f"✅ GPU ready: {torch.cuda.get_device_name(0)}")
print(f"   VRAM available: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

# ── Cell 3: Imports ───────────────────────────────────────────────────────────
import numpy as np
import torch
import torch.nn as nn
from PIL import Image, ImageDraw
from IPython.display import display
import insightface
from insightface.app import FaceAnalysis
from diffusers import AutoPipelineForInpainting, AutoencoderKL
from diffusers.utils import load_image
from transformers import SegformerImageProcessor, AutoModelForSemanticSegmentation

print("✅ Imports done")

# ── Cell 4: Upload your images ────────────────────────────────────────────────
# Upload a photo of the model (person) and a photo of the clothing item.

from google.colab import files

print("📂 Upload your MODEL image (photo of the person):")
uploaded_model = files.upload()
model_filename = list(uploaded_model.keys())[0]

print("\n📂 Upload your CLOTHING image (the garment you want to try on):")
uploaded_clothing = files.upload()
clothing_filename = list(uploaded_clothing.keys())[0]

# Load images
model_image    = Image.open(model_filename).convert("RGB")
clothing_image = Image.open(clothing_filename).convert("RGB")

# Preview
print("\n🧍 Model image:")
display(model_image.resize((256, 256)))
print("\n👕 Clothing image:")
display(clothing_image.resize((256, 256)))

# ── Cell 5: Load segmentation model ──────────────────────────────────────────
# Using the official SegFormer API instead of the pipeline wrapper (more reliable)

print("Loading SegFormer clothes segmentation model...")
seg_processor = SegformerImageProcessor.from_pretrained("mattmdjaga/segformer_b2_clothes")
seg_model     = AutoModelForSemanticSegmentation.from_pretrained("mattmdjaga/segformer_b2_clothes")
seg_model.eval()
print("✅ Segmentation model loaded")

# Label map from the model card
LABEL_MAP = {
    0:  "Background",  1:  "Hat",         2:  "Hair",
    3:  "Sunglasses",  4:  "Upper-clothes",5:  "Skirt",
    6:  "Pants",       7:  "Dress",        8:  "Belt",
    9:  "Left-shoe",   10: "Right-shoe",   11: "Face",
    12: "Left-leg",    13: "Right-leg",    14: "Left-arm",
    15: "Right-arm",   16: "Bag",          17: "Scarf"
}

# ── Cell 6: Load face detection model ────────────────────────────────────────
print("Loading InsightFace...")
face_app = FaceAnalysis(providers=["CUDAExecutionProvider", "CPUExecutionProvider"])
face_app.prepare(ctx_id=0, det_size=(640, 640))
print("✅ Face detection loaded")

# ── Cell 7: Segmentation helpers ──────────────────────────────────────────────

def get_segmentation_map(image: Image.Image) -> np.ndarray:
    """Run SegFormer and return a per-pixel label map (H x W)."""
    inputs  = seg_processor(images=image, return_tensors="pt")
    with torch.no_grad():
        outputs = seg_model(**inputs)
    logits = outputs.logits  # (1, num_labels, H/4, W/4)
    upsampled = nn.functional.interpolate(
        logits,
        size=image.size[::-1],   # (H, W)
        mode="bilinear",
        align_corners=False,
    )
    return upsampled.argmax(dim=1)[0].cpu().numpy()  # (H, W)


def labels_to_mask(seg_map: np.ndarray, include_labels: list) -> Image.Image:
    """Build a binary PIL mask from a list of label names."""
    label_ids = [k for k, v in LABEL_MAP.items() if v in include_labels]
    binary    = np.zeros_like(seg_map, dtype=np.uint8)
    for lid in label_ids:
        binary[seg_map == lid] = 255
    return Image.fromarray(binary)


def remove_face_from_mask(image: Image.Image, mask: Image.Image) -> Image.Image:
    """Black-out the face region in the mask so inpainting doesn't touch it."""
    img_np = np.array(image.convert("RGB"))
    faces  = face_app.get(img_np)
    if not faces:
        print("⚠️  No face detected — skipping face removal.")
        return mask

    bbox = faces[0]["bbox"].copy()  # [x1, y1, x2, y2]
    w    = bbox[2] - bbox[0]
    h    = bbox[3] - bbox[1]

    # Expand bounding box slightly so hair/neck are preserved
    bbox[0] -= w * 0.5
    bbox[2] += w * 0.5
    bbox[1] -= h * 0.5
    bbox[3] += h * 0.2

    draw = ImageDraw.Draw(mask)
    draw.rectangle([(bbox[0], bbox[1]), (bbox[2], bbox[3])], fill=0)
    return mask


def build_torso_mask(image: Image.Image) -> Image.Image:
    """Return a mask covering upper-body clothing area (excludes face)."""
    seg_map = get_segmentation_map(image)
    torso_labels = ["Upper-clothes", "Dress", "Belt", "Left-arm", "Right-arm", "Scarf"]
    mask = labels_to_mask(seg_map, torso_labels)
    mask = remove_face_from_mask(image, mask)
    return mask


def get_gender(image: Image.Image) -> str:
    """Detect gender from the model image using InsightFace. Returns 'male'/'female'/'unknown'."""
    img_np = np.array(image.convert("RGB"))
    faces  = face_app.get(img_np)
    if not faces:
        return "unknown"
    return "male" if faces[0]["gender"] == 1 else "female"

print("✅ Segmentation helpers ready")

# ── Cell 8: Generate and preview the mask ─────────────────────────────────────
print("Generating clothing mask...")
mask_image = build_torso_mask(model_image)

# Resize to 1024x1024 — SDXL native resolution
TARGET_SIZE = (1024, 1024)
model_image_resized = model_image.resize(TARGET_SIZE)
mask_image_resized  = mask_image.resize(TARGET_SIZE)

print("\n🗺️  Segmentation mask (white = region to replace):")
display(mask_image_resized.resize((256, 256)))

gender = get_gender(model_image)
print(f"👤 Detected gender: {gender}")

# ── Cell 9: Load SDXL pipeline ────────────────────────────────────────────────
# This downloads ~6 GB — takes a few minutes on first run.

print("Loading VAE...")
vae = AutoencoderKL.from_pretrained(
    "madebyollin/sdxl-vae-fp16-fix",
    torch_dtype=torch.float16,
)

print("Loading SDXL Inpainting pipeline...")
pipe = AutoPipelineForInpainting.from_pretrained(
    "diffusers/stable-diffusion-xl-1.0-inpainting-0.1",
    vae=vae,
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True,
).to("cuda")

print("Loading IP-Adapter...")
pipe.load_ip_adapter(
    "h94/IP-Adapter",
    subfolder="sdxl_models",
    weight_name="ip-adapter_sdxl.bin",
)
pipe.set_ip_adapter_scale(1.5)   # --higher = clothing more faithfully copied

# Optional: speed up with xformers if available
try:
    pipe.enable_xformers_memory_efficient_attention()
    print("⚡ xformers enabled")
except Exception:
    pass

print("✅ Pipeline ready")

"""I took this out of the cell 9, for times i need to change the ip_adapter_scale

"""

pipe.set_ip_adapter_scale(1.9)  # 0 to 1 — higher = clothing more faithfully copied

# ── Cell 10: Run try-on generation ───────────────────────────────────────────
# Tune these parameters if results aren't what you want:
#   strength        → higher = more creative but deviates more from original body
#   guidance_scale  → higher = sticks closer to the text prompt
#   num_steps       → more = better quality but slower (50 is a good balance)
#   ip_adapter_scale (set above) → higher = clothing image is more faithfully preserved
# ── Cell 10: Run try-on generation ───────────────────────────────────────────

if gender == "male":
    PROMPT = (
        "photorealistic editorial fashion photo, male model, flat athletic torso, "
        "well-fitted garment draping naturally over the body, correct garment silhouette, "
        "natural fabric folds following body contours, consistent studio lighting, sharp focus"
    )
    NEGATIVE_PROMPT = (
        "puffy chest, rounded bulge, balloon shape, breast shape, oversized fit, "
        "old clothing visible, mismatched garment, double layered clothing, "
        "ugly, low quality, deformed, bad anatomy, bad hands, blurry, watermark, extra limbs"
    )
elif gender == "female":
    PROMPT = (
        "photorealistic editorial fashion photo, female model, natural body shape, "
        "well-fitted garment draping naturally over the body, correct garment silhouette, "
        "natural fabric folds following body contours, consistent studio lighting, sharp focus"
    )
    NEGATIVE_PROMPT = (
        "flat shapeless torso, distorted proportions, oversized fit, "
        "old clothing visible, mismatched garment, double layered clothing, "
        "ugly, low quality, deformed, bad anatomy, bad hands, blurry, watermark, extra limbs"
    )
else:
    PROMPT = (
        "photorealistic editorial fashion photo, natural body shape, "
        "well-fitted garment draping naturally over the body, correct garment silhouette, "
        "natural fabric folds following body contours, consistent studio lighting, sharp focus"
    )
    NEGATIVE_PROMPT = (
        "distorted proportions, oversized fit, old clothing visible, mismatched garment, "
        "ugly, low quality, deformed, bad anatomy, bad hands, blurry, watermark, extra limbs"
    )

print(f"🎨 Generating try-on result — tuned for: {gender}")
generator = torch.Generator(device="cuda").manual_seed(42)

result = pipe(
    prompt           = PROMPT,
    negative_prompt  = NEGATIVE_PROMPT,
    image            = model_image_resized,
    mask_image       = mask_image_resized,
    ip_adapter_image = clothing_image,
    strength         = 0.90,    # raised from 0.60 — gives SDXL room to fully replace garment shape, no leftover bulge
    guidance_scale   = 8.0,     # slightly lowered from 9.5 — too high can over-emphasize "natural folds" into exaggerated puffiness
    num_inference_steps = 50,   # 50 is the sweet spot;
    generator        = generator,
).images[0]

print("✅ Done!")

# ── Cell 11: View and save result ─────────────────────────────────────────────
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3, figsize=(15, 6))
axes[0].imshow(model_image_resized);    axes[0].set_title("Original Model");    axes[0].axis("off")
axes[1].imshow(clothing_image);         axes[1].set_title("Clothing Input");    axes[1].axis("off")
axes[2].imshow(result);                 axes[2].set_title("Try-On Result");     axes[2].axis("off")
plt.tight_layout()
plt.savefig("tryon_comparison.png", dpi=150, bbox_inches="tight")
plt.show()

result.save("tryon_result.jpg", quality=95)
print("💾 Saved: tryon_result.jpg & tryon_comparison.png")

# Download to your machine
from google.colab import files
files.download("tryon_result.jpg")
files.download("tryon_comparison.png")

"""## 🔧 Troubleshooting

| Problem | Fix |
|---|---|
| CUDA out of memory | Reduce `num_inference_steps` to 30, or restart runtime |
| Clothing not showing correctly | Increase `ip_adapter_scale` to 1.0 or reduce `strength` to 0.85 |
| Face looks distorted | The face mask isn't working — check InsightFace detected a face in Cell 8 |
| Too slow | Use Colab Pro for A100 GPU — T4 takes ~3 min at 50 steps |
"""